version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install config
  build:
    commands:
      - echo "Zipping deployment package..."
      # - zip -r9 deplyment_package.zip node_modules
      # - cd ..
      - cd src
      - zip -R ../deplyment_package.zip "*.js"
      - cd ..
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name test-ctp-github-to-lambda-njs --zip-file fileb://deplyment_package.zip
      - echo "Done!"
